### ISSUE TITLE
AviatorScript TODO list

### ISSUE THREAD

**Issue by killme2008** [killme2008/aviator#206]
* [x] Simple IO lib
* [x] Main function and bootstrap shell to execute a script.
* [x] `load` and `require` function to load/require a script.
* [x] Update and add documents.
* [ ] char type
* [x] make string as a sequence.

**Comment by ChenLinXi** [comment]
很期待AviatorScript的新功能，顺便提几个小的优化点。

- compileScript()方法支持相对路径、URL；
Usage：便于集成配置中心，可动态导入AviatorScript

- AviatorScript支持动态参数；
1）Demo
let a = ${a};
let b = ${b};
c = a + b
2）Usage：
        Expression expression = AviatorEvaluator.getInstance().compileScript("example.av");
        Map<String, Object> env = new HashMap<>();
        env.put("b", 2);
        env.put("a", 2);
        Object ret = expression.execute(env);

- AviatorScript中的fn函数与AviatorFunction互相兼容
Usage：手动添加的AviatorFunction也可以在AviatorScript中使用

- AviatorScript支持Import
Usage：可以在一个AviatorScript里面注入其他AviatorScript

**Comment by killme2008** [comment]
1. 没明白什么意思，为什么要特别引入 `${a}` 的方式，目前已经支持你说的传入变量的方式，没有必要再 `let a = ${a};` 引用一层。
2. 可以的，两者定义的对象都是 `AviatorFunction`
3. 支持的，参见 [test_sqort.av](https://github.com/killme2008/aviator/blob/master/examples/test_qsort.av)，文档暂未编写。

**Comment by ChenLinXi** [comment]
> > 很期待AviatorScript的新功能，顺便提几个小的优化点。
> > 
> > * compileScript()方法支持相对路径、URL；
> >   Usage：便于集成配置中心，可动态导入AviatorScript
> > * AviatorScript支持动态参数；
> >   1）Demo
> >   let a = ${a};
> >   let b = ${b};
> >   c = a + b
> >   2）Usage：
> >   Expression expression = AviatorEvaluator.getInstance().compileScript("example.av");
> >   Map<String, Object> env = new HashMap<>();
> >   env.put("b", 2);
> >   env.put("a", 2);
> >   Object ret = expression.execute(env);
> > * AviatorScript中的fn函数与AviatorFunction互相兼容
> >   Usage：手动添加的AviatorFunction也可以在AviatorScript中使用
> > * AviatorScript支持Import
> >   Usage：可以在一个AviatorScript里面注入其他AviatorScript
> 
> 1. 没明白什么意思，为什么要特别引入 `${a}` 的方式，目前已经支持你说的传入变量的方式，没有必要再 `let a = ${a};` 引用一层。
> 2. 可以的，两者定义的对象都是 `AviatorFunction`
> 3. 支持的，参见 [test_sqort.av](https://github.com/killme2008/aviator/blob/master/examples/test_qsort.av)，文档暂未编写。

有没有可能提供一下这样的方法：compileScript(final String cacheKey, final File file ,final boolean cached)
Usage：我想把AviatorScript集成到公共配置中心，与代码解耦；
